routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('index');

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('cek_email_aktif', 'Auth\LoginController@cek_email_aktif')->name('cek_email_aktif');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/home', 'Member\MemberController@StructureMember')->name('home');
// Route::get('/', 'Member\MemberController@StructureMember')->middleware('auth')->name('member.structure');

Route::post('register/store', 'Auth\RegisterController@store')->name('register.store');

// Route::get('payment/confirmation/{email}', 'Payment\PaymentConfirmationController@index')->name('payment.confirmation.index');
Route::get('payment/confirmation', 'Payment\PaymentConfirmationController@index')->name('payment.confirmation.index');
Route::post('payment/confirmation/create', 'Api\Cashback\CashbackController@storePaymentConfirmation')->name('payment.confirmation.create');
// Route::post('payment/confirmation/create', 'Payment\PaymentConfirmationController@create')->name('payment.confirmation.create');
Route::get('payment/credit-card', 'Payment\PaymentCreditCardController@index')->name('payment.credit_card');

//email
Route::get('get_data_email/{base64}', 'Member\Services\MailService@get_data_email')->name('get_data_email');
// Route::get('register_after_send_email/{base64}', 'Member\Services\MailService@register_after_send_email')->name('register_after_send_email');

//checkout
Route::post('checkout/{customer_code}/group/{user_groups}', 'Member\Services\MailService@checkout')->name('checkout');


Route::prefix('member')->name('member.')->group(function() {
    Route::get('structure', 'Member\MemberController@StructureMember')->middleware('auth')->name('structure');
    Route::get('structure_one/{id}', 'Member\MemberController@StructureMemberOne')->middleware('auth')->name('structure_one');
    Route::get('create', 'Member\MemberController@create')->name('create');
    Route::post('storeMember', 'Member\MemberController@storeMember')->name('storeMember');
    Route::get('create/{customer_code}/group/{user_groups}', 'Member\MemberController@create_member')->name('create_member');
    Route::post('storeCustomer', 'Member\MemberController@storeCustomer')->name('storeCustomer');
    Route::get('cek_ktp', 'Member\MemberController@cek_ktp')->name('cek_ktp');
    Route::get('cek_email', 'Member\MemberController@cek_email')->name('cek_email');
    // Route::get('cek_email_aktif', 'Member\MemberController@cek_email_aktif')->name('cek_email_aktif');
    Route::get('update_status_email/{email}', 'Member\Services\MailService@update_status_email')->name('update_status_email');
    // Route::get('ref_code', 'Member\MemberController@ref_code')->name('ref_code');

});

// Route::get('data_email/{email}', 'Member\Services\MailService@update_status_email')->name('update_status_email');

// Route::get('/verify/{token}', 'verifyController@verify')->name('verify');

// Route::post('send',[
//     'as' => 'send.email',
//     'uses' => 'Member\Services\Member_services@sendEmail'
// ]);

app/Http/Controllers/Member/MemberController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use App\Models\Address_model;
use App\Models\Member_model;
use App\Models\Users_model;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MemberController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function StructureMember(Request $request)
    {
        $auth = Auth::user();
        $memberParent = Member_model::where('user_id', $auth->id)->first();
        $memberChild = Member_model::where([
            'identity' => $memberParent->customer_code,
            'user_groups' => $memberParent->user_groups,
        ])->get();

        $jumlahMemberChild = Member_model::where([
            'identity' => $memberParent->customer_code,
            'user_groups' => $memberParent->user_groups,
        ])->count();

        function halo($dataGroup, $dataUserGroup)
        {
            $dataGroup;
            $memberChild = Member_model::where([
                'groups' => $dataGroup,
                'user_groups' => $dataUserGroup,
            ])->first();

            $jumlahMemberChild = Member_model::where([
                'groups' => $dataGroup,
                'user_groups' => $dataUserGroup,
            ])->count();
            
            //bisa ngga sih $memberChild di tampilin dalam bentuk array ?? atau mungkin kamu bisa bantu kasih aku harus pakai apa wkwkwkwkw
            //Jadi ceritanya, aku mau ambil data 'groups' yang paling kecil di dalam tabel 'customer' yang bernilai kosong berdasarkan kepala yang login.
            //Sistem ini kalo di tampilin bentuknya kayak MLM , nah kepala paling atas itu dia yang login. 
            //Kepala sebagai Parent, nanti anaknya ada 2 sebagai child, identitasnya itu jika 'customer_code' punya kepala = 'identity' di Child
            //nanti child punya anak lagi jadi grandChild dan begitu seterusnya
            
            //rencana nanti di tampilan pohon faktornya itu bisa nge add hanya pada baris terkecil 
            
            

        }

        for ($i = 0; $i < 2; $i++) {
            $memberGrandChild[$i] = Member_model::where([
                'identity' => $memberChild[$i]->customer_code,
                'user_groups' => $memberChild[$i]->user_groups,
                'ktp' => null,
            ])->first();

            $memberGrandChildIsset[$i] = Member_model::where([
                'identity' => $memberChild[$i]->customer_code,
                'user_groups' => $memberChild[$i]->user_groups,
            ])->first();

        }

        if (empty($memberGrandChild[0]->groups)) {
            $dataGroup = $memberGrandChildIsset[0]->groups + 1;
            $dataUserGroup = $memberGrandChildIsset[0]->user_groups;

            halo($dataGroup, $dataUserGroup);

        } else {
            echo $dataGroup = $memberGrandChild[0]->groups;
        }

        die;

// batas tampilan

        $member = Member_model::where('user_id', $auth->id)->first();
        if (isset($member)) {
            $countMember = Member_model::where([
                'identity' => $member->customer_code,
                'user_groups' => $member->user_groups,
            ])->count();
        } else {
            $countMember = 0;
        }

        $first_member = Member_model::where('user_id', $auth->id)
            ->whereHas('users', function ($q) {
                $q->where('active', 1);
            })
            ->first();
        // return $dataGroup;

        return view('member.structure')->with([
            'first_member' => $first_member,
            'count_table' => $countMember,
            'id_user' => $auth->id,
            'data_group' => $dataGroup,
        ]);
    }

    public function StructureMemberOne($id)
    {

        $member = Member_model::where('user_id', $id)->first();
        if (isset($member)) {
            $countMember = Member_model::where([
                'identity' => $member->customer_code,
                'user_groups' => $member->user_groups,
            ])->count();
        } else {
            $countMember = 0;
        }

        $first_member = Member_model::where('user_id', $id)
            ->whereHas('users', function ($q) {
                $q->where('active', 1);
            })
            ->first();

        return view('member.structure')->with([
            'first_member' => $first_member,
            'count_table' => $countMember,
            'id_user' => $id,
        ]);
    }

    public function create($value = '')
    {
        $auth = Auth::user();

        $member = Member_model::where('user_id', $auth->id)->first();
        if (isset($member)) {

            $select_position_min = Member_model::where([
                'identity' => $member->customer_code,
                // 'ktp'=>null
            ])->first();

            $select_position_max = Member_model::where([
                'identity' => $member->customer_code,
                // 'ktp'=>null
            ])->get()->max();

            // $select_position_min = $select_position->first();
            // $select_position_max = $select_position_min+1;
            if (empty($select_position_max->ktp)) {
                $select_tampil_max = $select_position_max->customer_code;
            } else {
                $select_tampil_max = null;
            }

            if (empty($select_position_min->ktp)) {
                $select_tampil_min = $select_position_min->customer_code;
            } else {
                $select_tampil_min = null;
            }

            $user_groups = $member->user_groups;
        } else {
            $select_tampil_min = null;
            $select_tampil_max = null;
            $user_groups = null;
        }

        // return $select_tampil_min;
        // return $select_position_max;

        // $select_position = Member_model::where('ktp', null)->get();

        // $referal_code_db = Member_model::where('identity', 1)->first();
        $referal_code_db = Member_model::where('user_id', $auth->id)->first();
        if (isset($referal_code_db)) {
            $referal_code = $referal_code_db;
        } else {
            $referal_code = '';
        }
        // $query =
        // $referal_code = base64_encode();

        return view('member.create')->with([
            // 'select_position' => $select_position,
            'select_tampil_min' => $select_tampil_min,
            'select_tampil_max' => $select_tampil_max,
            'user_groups' => $user_groups,
            'referal_code' => $referal_code,
        ]);

    }

    public function create_member($customer_code, $user_groups)
    {
        $auth = Auth::user();
        $customer = Member_model::where('user_id', $auth->id)->first();
        return view('member.create_member')->with([
            'customer' => $customer,
            'customer_code' => $customer_code,
            'user_groups' => $user_groups,
            'user' => $auth,
        ]);

    }

    public function storeCustomer(Request $req)
    {
        return view('member.cekout');
    }

    public function storeMember(Request $req)
    {

        // jika jumlah tabel nya 0, maka create table, dan menambah 2 field baru
        // jika ada tabelnya, maka update tabel berdasarkan customer_code yang sudah di inputkan dan generate field

        $auth = Auth::user();
        // return $auth->id;
        $count_table = DB::table('customers')->where('customer_code', $req->customer_code)->count();

        if ($count_table == 0) {
            //perintah tambah data
            $user_isi = Users_model::create([
                'name' => $req->first_name,
                'email' => $req->email,
                'password' => \Hash::make($req->password),
                // 'token'=> str_random(25)
            ]);

            $address_isi = Address_model::create([
                'address' => $req->address,
            ]);

            $cust_isi = Member_model::create([
                'referral_code' => base64_encode($user_isi->id),
                'customer_code' => 1,
                'first_name' => $req->first_name,
                'last_name' => $req->last_name,
                'ktp' => $req->ktp,
                'birth_date' => $req->birth_date,
                'gender' => $req->gender,
                'phone' => $req->phone,
                'address_id' => $address_isi->id,
                'user_id' => $user_isi->id,
                'groups' => 1,
                'identity' => '0',
                'user_groups' => 1,
            ]);

            // $user=$req->email;
            ///sending email
            // event(new UserActivationEmail($user));

            //perintah tambah field kosong
            $count_table = DB::table('customers')->count();
            $perulangan = $count_table + 1;
            for ($i = 1; $i <= $perulangan; $i++) {
                $user = Users_model::create([
                    'name' => null,
                    'email' => null,
                    'password' => null,
                ]);

                $address = Address_model::create([
                    'address' => null,
                ]);

                $child = $count_table + $i;
                $cust = Member_model::create([
                    'referral_code' => base64_encode($user->id),
                    'customer_code' => $count_table + $i,
                    'first_name' => null,
                    'last_name' => null,
                    'ktp' => null,
                    'birth_date' => null,
                    'gender' => null,
                    'phone' => null,
                    'address_id' => $address->id,
                    'user_id' => $user->id,
                    'groups' => 2,
                    'identity' => 1,
                    'user_groups' => 1,
                ]);
            }

            // $referalcode = base64_encode($user->id);

            //verifikasi email

resources/views/member/create.blade.php
@extends('layouts.auth')

@section('title')
<title>Cashback - Add Member</title>
@endsection

@push('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style type="text/css">
.error {
    color: #dc3545;
}

.form-control:focus {
    border-color: #007bff;
    box-shadow: inset 0 1px 1px rgba(40, 167, 69, 0.25), 0 0 8px rgba(40, 167, 69, 0.6);
}

.custom-radio .custom-control-input:checked~.custom-control-label::before,
.custom-radio .custom-control-input:checked~.custom-control-label::after {
    background-color: #007bff;
    border-radius: 50%;
}

.custom-radio .custom-control-input:focus~.custom-control-label::before {
    box-shadow: 0 0 0 1px #fff, 0 0 0 0.2rem rgba(40, 167, 69, 0.25);
}

.custom-checkbox .custom-control-input:checked~.custom-control-label::before,
.custom-checkbox .custom-control-input:checked~.custom-control-label::after {
    background-color: #007bff;
    border-radius: 30%;
}

.custom-checkbox .custom-control-input:focus~.custom-control-label::before {
    box-shadow: 0 0 0 1px #fff, 0 0 0 0.2rem rgba(40, 167, 69, 0.25);
}
</style>
@endpush

@section('content')
    <div class="container" style="margin-top : 10px; margin-bottom:50px;">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="fdb-box fdb-touch" style="border-top: solid 5px #007bff;">
                    <div class="row">
                        <div class="col text-center">
                            <h1 style="text-align: center; margin-left:20px; margin-top:20px;">Add Member</h1>
                        </div>
                    </div>
                    @if(session()->has('alert'))
                    <div class="row">
                        <div class="alert alert-danger" role="alert">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {!! session('alert') !!}
                        </div>
                    </div>
                    @endif
                    <div class="row justify-content-center">
                        <form class="member" id="formmember" method="post" action="{{ route('member.storeMember') }}" aria-label="{{ __('Register') }}">
                        {{-- <form class="member" id="formmember" method="post" action="{{ route('send.email') }}" aria-label="{{ __('Register') }}"> --}}
                            @csrf
                            <hr class="mb-4">
                            <div class="mb-3">
                                <label for="referral_code">Your Referral Code</label>

                                <input type="text" class="form-control" id="referral_code" name="referral_code" value="@if (isset($referal_code->referral_code)) {{$referal_code->referral_code}} @endif" readonly >
                                <div class="label-code"></div>
                            </div>
                            <div class="mb-3">


                                <label for="customer_code">Reference Code <span class="text-danger">*</span></label>
                                {{-- <input type="text" class="form-control" id="customer_code" name="customer_code"> --}}
                                {{-- <select class="form-control" id="customer_code" name="customer_code" onchange="referal_code()"> --}}
                                <select class="form-control" id="customer_code" name="customer_code" >

                                    {{-- @foreach ($select_position as $key => $value) --}}
                                {{-- <option value="{{$value->customer_code}}">{{$key+1}}</option> --}}
                                {{-- @endforeach --}}
                                {{-- <option value="2">2</option> --}}

                                {{-- {{-- <option value="{{$select_position['0']}}">1</option> --}}


                                @if (isset($select_tampil_min))
                                <option value="{{$select_tampil_min}}">1</option>
                                @endif
                                @if (isset($select_tampil_max))
                                <option value="{{$select_tampil_max}}">2</option>
                                @endif
                                @if ($select_tampil_min == NULL && $select_tampil_max ==  NULL)
                                <option value="1"></option>
                                @endif
                                {{-- <option value="{{$select_position_max->customer_code}}">2</option> --}}


                                </select>
                                {{-- <input type="hidden" name="ref_generate" id="ref_generate" value="aaa">                                 --}}
                                <div class="label-code"></div>
                            </div>

                            <script>
                                // function referal_code(){
                                //     var cust_code = document.getElementById("customer_code").value;
                                //     $.ajax({
                                //                 url:"{{url('member/ref_code')}}",
                                //                 data:"cust_code="+cust_code,
                                //                 success: function (html) {
                                //             load();
                                //         }
                                //     })
                                // }

                                // function load(){
                                //     // alert($_GET['cust_code']);
                                //     document.getElementById('referral_code').value = document.getElementById('customer_code').value;
                                //     alert('load sukses');
                                // }
                            </script>

                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="first_name">First Name<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="last_name">Last Name<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name">
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="ktp">ID Number ( KTP ) <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="ktp" name="ktp" maxlength="16" placeholder="ID Number">
                            </div>
                            <div class="mb-3">
                                <label for="birth_date">Birthdate<span class="text-danger">*</span></label>
                                <input type="date" class="form-control" name="birth_date" placeholder="DD-MM-YYYY">
                            </div>
                            <div class="mb-3">
                                <label for="gender">Gender<span class="text-danger">*</span></label>
                                <div class="d-block">
                                    <div class="custom-control custom-radio custom-control-inline">
                                        <input id="male" name="gender" type="radio" class="custom-control-input" value="M" data-error=".gender-error" checked>
                                        <label class="custom-control-label" for="male">Male</label>
                                    </div>
                                    <div class="custom-control custom-radio custom-control-inline">
                                        <input id="female" name="gender" type="radio" class="custom-control-input" value="F" data-error=".gender-error">
                                        <label class="custom-control-label" for="female">Female</label>
                                    </div>
                                </div>
                                <div class="gender-error"></div>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Mobile<span class="text-danger">*</span></label><br>
                                <input type="tel" class="form-control" id="phone" name="phone" maxlength="13" placeholder="Mobile">
                            </div>
                            <div class="mb-3">
                                <label for="address">Address<span class="text-danger">*</span></label>
                                <textarea class="form-control" id="address" name="address" rows="3" placeholder="Address"></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="email">Email<span class="text-danger">*</span></label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                                <input type="hidden" name="user_groups" value="{{$user_groups}}">
                                {{-- <input type="hidden" name="user_groups" value="{{$user_groups}}"> --}}
                            </div>
                            {{-- <div class="mb-3">
                                <label for="password">Password<span class="text-danger">*</span></label>
                                <input type="password" class="form-control" id="password" name="password">
                            </div>
                            <div class="mb-3">
                                <label for="confirm_password">Confirm Password<span class="text-danger">*</span></label>
                                <input type="password" class="form-control" id="confirm_password" name="confirm_password">
                            </div> --}}
                            <hr class="mb-4">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.18.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.18.0/additional-methods.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#formmember").validate({
        ignore: [],
        rules: {
            first_name: {
                required: true
            },
            last_name: {
                required: true
            },
            // customer_code: {
            //     required: true
            // },
            ktp: {
                required:true,
                digits: true,
                minlength: 16,
                remote: {
                    url: "{{url('member/cek_ktp')}}",
                    type: "get"
                }


            },
            email: {
                required: true,
                email: true,
                remote: {
                    url: "{{url('member/cek_email')}}",
                    type: "get"
                }
            },
            gender: {
                required: true
            },
            birth_date: {
                required: true
            },
            phone: {
                required: true,
                digits: true
            },
            address: {
                required: true
            },
            password: {
                required: true
            },
            confirm_password: {
                required: true,
                equalTo: '#password'
            },

        },
        messages: {
            ktp: {
                remote: "KTP already exists."
            },
            email: {
                remote: "Email already exists."
            }
        },
        errorElement: 'div',
        errorPlacement: function(error, element) {
            var placement = $(element).data('error');
            if (placement) {
                $(placement).append(error)
            } else {
                error.insertAfter(element);
            }
        }
    });

    $('#birth_date').datepicker({
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "1900:+0",
        onSelect: function() {
            $('#birth_date').removeClass('error');
            $('#birth_date + label').remove();
        },
        onClose: function() {
            $(this).trigger("focus").trigger("blur");
        }
    });

});
</script>
@endpush